Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_location'.
Couldn't create message for template 'utter_location'.
Couldn't create message for template 'utter_location'.
Couldn't create message for template 'utter_location'.
Couldn't create message for template 'utter_location'.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_location'.
Couldn't create message for template 'utter_location'.
Couldn't create message for template 'utter_location'.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_washroom_location'.
Couldn't create message for template 'utter_washroom_location'.
Couldn't create message for template 'utter_event'.
Couldn't create message for template 'utter_event'.
Couldn't create message for template 'utter_washroom_location'.
Couldn't create message for template 'utter_washroom_location'.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_event'.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_event'.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Couldn't create message for template 'utter_event'.
Couldn't create message for template 'utter_event'.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to run custom action 'action_event'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f723df57ac8>: Failed to establish a new connection: [Errno 111] Connection refused',))
Encountered an exception while running action 'action_event'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f250c52f358>: Failed to establish a new connection: [Errno 111] Connection refused',))
Encountered an exception while running action 'action_event'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event_time'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event_time'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event_time'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event_time'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event_time'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event_time'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to run custom action 'action_event_location'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event_location'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to run custom action 'action_event_time'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event_time'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to run custom action 'action_event_time'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event_time'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to run custom action 'action_event_time'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event_time'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to run custom action 'action_event_time'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event_time'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_event_time'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event_time'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/rasa_core/channels/channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/rasa_core/channels/channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/rasa_core/channels/channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/rasa_core/channels/channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/rasa_core/channels/channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/rasa_core/channels/channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/rasa_core/channels/channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/rasa_core/channels/channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/rasa_core/channels/channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/rasa_core/channels/channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/rasa_core/channels/channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/rasa_core/channels/channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_food_location'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_food_location'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to run custom action 'action_event_location'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_event_location'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/rasa_core/channels/channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/rasa_core/channels/channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/rasa_core/channels/channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/rasa_core/channels/channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/rasa_core/channels/channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "/home/pkmn/anaconda3/envs/ML-env/lib/python3.6/site-packages/rasa_core/channels/channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Encountered an exception while running action 'action_event_time'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Rasa Core server is up and running on http://localhost:5005
